import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/nav/footer";
import Header from "@/components/nav/header";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        /*         className="bg-gray-100 min-h-[100dvh] grid grid-rows-[1fr_auto]"
         */ className=" min-h-[100dvh] flex flex-col"
      >
        <Header />

        <div className="flex-1 grid">{children}</div>
        <Footer />
        <Toaster richColors />
      </body>
    </html>
  );
}
